# 土地銀行數位種子人才發展計劃

> Python 資料處理與金融分析應用

[郭耀仁](https://hahow.in/@tonykuoyj) | <yaojenkuo@ntu.edu.tw>

## 目錄

- Python 數據分析模組介紹（P.3）
- NumPy 基本概念與應用 - Pandas 資料讀取、清洗與整理（P.13）
- 個案討論：使用 Python 數據分析模組實踐「財務自由的世界，財務分析就是一場投資的戰爭」的部分選股程序（P.141）
- 實作：檢視各小組題目中 Python 數據分析模組的需求，以 mock data 測試能否順利完成（P.143）

## Python 數據分析模組介紹

## Python 數據分析模組

- NumPy
- Pandas

## 什麼是 NumPy

> NumPy 是 Numeric Python 的簡稱，是 Python 最重要的資料科學模組之一。NumPy 創造了 `ndarray` 的資料結構類別以及大量的通用函數與聚合函數，讓 Python 使用者能夠對進行快速的數值計算、使用統計函數、進行線性代數運算以及操作隨機的模擬任務等。

來源：<https://numpy.org/>

## （沒什麼用的冷知識）NumPy 的前身為兩個模組

- 1990 年代中期誕生的` Numeric` 與 `Numarray` 模組。
- NumPy 於 2005 集兩者之大成問世。

來源：<https://www.nature.com/articles/s41586-020-2649-2>

## 根據說明文件的範例載入

來源：<https://numpy.org/doc/stable/user/absolute_beginners.html#how-to-import-numpy>

In [1]:
import numpy as np

## NumPy 的核心功能

1. 使用 `ndarray` 來進行數值操作。
2. 使用模組定義的函數對 `ndarray` 進行數值運算。
3. `ndarray` 是其他資料科學模組 Pandas、Matplotlib 與 Scikit-Learn 的基石。

## 什麼是 Pandas

> Pandas 是 Python 處理表格式資料（Tabular data）的第三方模組，它創造了 `Index`、`Series` 與 `DataFrame` 的資料結構類別，讓 Python 在面對表格式資料時能夠用更直覺的觀念操作。

來源：<https://github.com/pandas-dev/pandas>

## （沒什麼用的冷知識）Pandas 跟熊貓「沒有關係」

1. **Pan**el(自從版本 0.20.0 之後棄用)
2. **Da**taFrame
3. **S**eries

![](https://media.giphy.com/media/46Zj6ze2Z2t4k/giphy.gif)

來源：<https://media.giphy.com/media/46Zj6ze2Z2t4k/giphy.gif>

## 根據說明文件的範例載入

來源：<https://pandas.pydata.org/docs/user_guide/10min.html>

In [2]:
import pandas as pd

## 入門 Pandas 的第一步就是掌握 `Index`、`ndarray`、`Series` 與 `DataFrame` 四個資料結構類別彼此之間的關係

- `Series` 由 `Index` 與 `ndarray` 組合而成。
- `DataFrame` 由數個共享同一個 `Index` 的 `Series` 組合而成。

## NumPy 基本概念與應用 - Pandas 資料讀取、清洗與整理

## 從 `list` 創造 `ndarray`

In [3]:
prime_list = [2, 3, 5, 7, 11]
prime_array = np.array(prime_list)
print(prime_array)
print(type(prime_array))

[ 2  3  5  7 11]
<class 'numpy.ndarray'>

##  利用 NumPy 函數創造內容元素相同的 `ndarray`

- `np.zeros()`
- `np.ones()`
- `np.full()`

In [4]:
print(np.zeros(5, dtype=int))
print(np.ones(5, dtype=float))
print(np.full(5, 6))

[0 0 0 0 0]
[1. 1. 1. 1. 1.]
[6 6 6 6 6]

## 利用 NumPy 函數創造數列型態的 `ndarray`

- `np.arange(start, stop, step)`
- `np.linspace(start, stop, num)` 值得注意的是 `stop` 參數預設為包含。

In [5]:
print(np.arange(1, 11, 2))
print(np.linspace(1, 9, 5, dtype=int))

[1 3 5 7 9]
[1 3 5 7 9]

## 利用 `np.random` 中的函數創造隨機性的 `ndarray`

In [6]:
m = 10000
uniform_array = np.random.random(m) # module.function()
normal_array = np.random.normal(0, 1, m)
randint_array = np.random.randint(1, 7, size=m)
print(uniform_array)
print(normal_array)
print(randint_array)

[0.35759177 0.26482792 0.341589   ... 0.4113     0.15994867 0.05936431]
[ 1.49876232  0.541779    0.89889343 ...  0.73282694 -0.16239335
 -1.67578903]
[5 3 5 ... 6 3 4]

## 常用的 `ndarray` 屬性

- `ndarray.ndim` 維度數。
- `ndarray.shape` 外型。
- `ndarray.size` 元素個數。
- `ndarray.dtype` 資料類別。

In [7]:
prime_list = [2, 3, 5, 7, 11]
prime_array = np.array(prime_list)
print(prime_array.ndim)
print(prime_array.shape)
print(prime_array.size)
print(prime_array.dtype)

1
(5,)
5
int64

## 不同維度數的 `ndarray` 有不同的暱稱

- 零維 `ndarray`：純量（Scalar）。
- 一維 `ndarray`：向量（Vector）。
- 二維 `ndarray`：矩陣（Matrix）。
- 三維或者 n 維 `ndarray`：張量（Tensor）。

## 純量、向量、矩陣與張量外型示意圖

![Imgur](https://i.imgur.com/81fM6Hf.png)

來源：<https://dev.to/juancarlospaco/tensors-for-busy-people-315k>

## `ndarray` 與 `list` 相同的地方

- indexing/slicing 的語法。
- 能夠以 indexing 更新。

## indexing 的語法

`ndarray` 採用兩個方向的索引機制：

1. 由左至右：「從 0 開始」的索引機制。
2. 由右至左：「從 -1 開始」的索引機制。

In [8]:
primes_array = np.array([2, 3, 5, 7, 11])
print("From start to stop:")
print(primes_array[0])
print(primes_array[1])
print(primes_array[2])
print(primes_array[3])
print(primes_array[primes_array.size - 1])
print("From stop to start:")
print(primes_array[-1])
print(primes_array[-2])
print(primes_array[-3])
print(primes_array[-4])
print(primes_array[-primes_array.size])

From start to stop:
2
3
5
7
11
From stop to start:
11
7
5
3
2

## slicing `[start:stop:step]`

除了可以取出特定位置的單個資料值，`ndarray` 也支援擷取特定片段，藉此獲得一個較短長度 `ndarray` 的語法。

- `start` 起始位置（包含）。
- `stop` 終止位置（排除）。
- `step` 間隔。

In [9]:
print(primes_array[::])   # default
print(primes_array[::2])  # step=2
print(primes_array[:3])   # stop=5, exclusive
print(primes_array[3:])   # start=5, inclusive
print(primes_array[::-1]) # step=-1, reverse

[ 2  3  5  7 11]
[ 2  5 11]
[2 3 5]
[ 7 11]
[11  7  5  3  2]

## 能夠以 indexing 更新

In [10]:
primes_array = np.array([2, 3, 5, 7, 11])
print(primes_array)   # before update
primes_array[-1] = 13 # update
print(primes_array)   # after update

[ 2  3  5  7 11]
[ 2  3  5  7 13]

## `ndarray` 與 `list` 相異的地方

- indexing 二維以上的 `ndarray` 可以用更便捷的語法 `[i, j, k, ...]`
- 同質性資料結構類別。
- 支援元素操作（Elementwise）運算。
- 支援特殊的 indexing 語法。

## indexing 二維以上的 `ndarray` 可以用 `ndarray` 便捷的語法 `[i, j, k, ...]`

In [11]:
matrix = np.array([[5, 5],
                   [6, 6],
                   [55, 66]])
print(matrix)
print(matrix[2, 1]) # 66 locates at [2, 1]

[[ 5  5]
 [ 6  6]
 [55 66]]
66

In [12]:
print(matrix[:, 1])
print(matrix[:, [1]]) # keep dimension

[ 5  6 66]
[[ 5]
 [ 6]
 [66]]

## 同質性資料結構類別

In [13]:
heterogeneous_list = [False, True, 5566, 55.66, 'Luke Skywalker']
for element in heterogeneous_list:
    print(type(element))

<class 'bool'>
<class 'bool'>
<class 'int'>
<class 'float'>
<class 'str'>

In [14]:
homogeneous_array = np.array(heterogeneous_list)
for element in homogeneous_array:
    print(type(element))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>

## 支援元素操作（Elementwise）運算

In [15]:
# list does not support elementwise
primes_list = [2, 3, 5, 7, 11]
try:
    primes_list**2
except TypeError as error_message:
    print(error_message)

unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [16]:
# ndarray supports elementwise
primes_array = np.array(primes_list)
primes_array**2

array([  4,   9,  25,  49, 121])

## 支援特殊的 indexing 語法

- Fancy indexing
- Boolean indexing

## 什麼是 Fancy indexing

對應 `ndarray` 時中括號允許傳入 `list`，藉此可以更有彈性地取出 `ndarray` 中的元素。

In [17]:
primes_list = [2, 3, 5, 7, 11]
try:
    primes_list[[0, 1, 4]]
except TypeError as error_message:
    print(error_message)

list indices must be integers or slices, not list

In [18]:
primes_array = np.array([2, 3, 5, 7, 11])
print(primes_array)
print(primes_array[[0, 1, 4]])

[ 2  3  5  7 11]
[ 2  3 11]

## 什麼是 Boolean indexing

對應 `ndarray` 時中括號允許傳入由 `bool` 組成的相同長度 `list` 或 `ndarray`，藉此可以更有彈性地取出 `ndarray` 中的元素。

In [19]:
primes_list = [2, 3, 5, 7, 11]
try:
    primes_list[[False, True, True, True, True]]
except TypeError as error_message:
    print(error_message)

list indices must be integers or slices, not list

In [20]:
primes_array = np.array([2, 3, 5, 7, 11])
print(primes_array)
print(primes_array[[False, True, True, True, True]])
print(primes_array % 2 == 1)
print(primes_array[primes_array % 2 == 1])

[ 2  3  5  7 11]
[ 3  5  7 11]
[False  True  True  True  True]
[ 3  5  7 11]

## 常用的 `ndarray` 操作

- 調整外型。
- 複製。
- 合併。
- 分割。

## 調整外型

- `ndarray.reshape()`：調整為指定外型 `(..., m, n)`
- `ndarray.ravel()`：調整為一維 `(m,)`

In [21]:
array_range = np.arange(1, 13)
print(array_range)
print(array_range.shape)
print(array_range.reshape(3, 4))
print(array_range.reshape(3, 4).shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)

## 在其他維度已經決定時可以方便地指定 `-1` 給最後一個維度

In [22]:
print(array_range.reshape(3, -1))
print(array_range.reshape(-1, 3))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

## 使用 `ndarray.ravel()` 調整成一維

In [23]:
array_range = np.arange(1, 13).reshape(3, -1)
print(array_range.shape)
print(array_range.ndim)
print(array_range.ravel().shape)
print(array_range.ravel().ndim)

(3, 4)
2
(12,)
1

## 複製

- 透過物件命名參照並不會真的複製，會讓兩個物件名稱共享一個 `ndarray` 的資料值，但是卻能有不同的外型。
- 使用 `ndarray.copy()` 明確地複製。

In [24]:
vector = np.arange(1, 10)
matrix = vector.reshape(3, 3)
matrix[1, 1] = 5566
print(vector)
print(matrix)

[   1    2    3    4 5566    6    7    8    9]
[[   1    2    3]
 [   4 5566    6]
 [   7    8    9]]

## 使用 `ndarray.copy()` 明確地複製

In [25]:
vector = np.arange(1, 10)
matrix = vector.copy().reshape(3, 3)
matrix[1, 1] = 5566
print(vector)
print(matrix)

[1 2 3 4 5 6 7 8 9]
[[   1    2    3]
 [   4 5566    6]
 [   7    8    9]]

## 合併

使用 `np.concatenate()` 函數合併。

- 指定參數 `axis=0` 垂直合併（預設值）。
- 指定參數 `axis=1` 水平合併。

In [26]:
array_a = np.arange(1, 5).reshape(2, 2)
array_b = np.arange(5, 9).reshape(2, 2)
print(np.concatenate((array_a, array_b)))         # default, axis=0
print(np.concatenate((array_a, array_b), axis=1)) # axis=1

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]

## 分割

使用 `np.split()` 函數分割。

- 指定參數 `axis=0` 垂直分割（預設值）。
- 指定參數 `axis=1` 水平分割。

In [27]:
array_range = np.arange(20).reshape(-1, 2)
upper_array, lower_array = np.split(array_range, 2) # split to 2 ndarrays
print(upper_array)
print(lower_array)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]

## 如果以 `list` 傳入參數則表示分割的索引值

In [28]:
array_range = np.arange(20).reshape(-1, 2)
upper_array, lower_array = np.split(array_range, [2]) # split on index 2
print(upper_array)
print(lower_array)

[[0 1]
 [2 3]]
[[ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]

In [29]:
array_range = np.arange(20).reshape(-1, 2)
left_array, right_array = np.split(array_range, 2, axis=1)
print(left_array)
print(right_array)

[[ 0]
 [ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]
 [12]
 [14]
 [16]
 [18]]
[[ 1]
 [ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]
 [13]
 [15]
 [17]
 [19]]

## NumPy 提供非常豐富的數值運算函數

- 通用函數（Universal functions）。
- 聚合函數（Aggregate functions）。

## 什麼是通用函數

通用函數是具備向量化（Vectorized）特性的函數，接受固定數量、外型的輸入並對應相同數量、外型的輸出。

In [30]:
array_range = np.arange(10)
print(array_range)
print(np.power(array_range, 2)) # np.power() is a universal function
print(np.exp(array_range))      # np.exp() is a universal function

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]

## 轉換純量函數為通用函數

使用 `np.vectorize()` 函數將只能作用在單一資料值上的函數轉換為通用函數。

In [31]:
def is_prime(x):
    number_of_divisors = 0
    for integer in range(1, x + 1):
        if x % integer == 0:
            number_of_divisors += 1
    return number_of_divisors == 2

try:
    is_prime(np.arange(10))
except TypeError as error_message:
    print(error_message)

only integer scalar arrays can be converted to a scalar index

In [32]:
vectorized_is_prime = np.vectorize(is_prime)
vectorized_is_prime(np.arange(10))

array([False, False,  True,  True, False,  True, False,  True, False,
       False])

## 什麼是聚合函數

聚合函數是能夠將多個資料值輸入摘要為單一值輸出的函數。

In [33]:
array_range = np.arange(1, 16).reshape(3, 5)
np.sum(array_range)

120

## NumPy 的聚合函數有兩個值得注意的特性

1. 可以沿指定的軸（axis）進行聚合。
2. 針對含有 `np.nan`（Not a Number）的 `ndarray` 有相對應名稱的聚合函數可以運算。

In [34]:
# Aggregate along specific axis
array_range = np.arange(1, 16, dtype=float).reshape(3, 5)
print(np.sum(array_range))
print(np.sum(array_range, axis=0))
print(np.sum(array_range, axis=1))

120.0
[18. 21. 24. 27. 30.]
[15. 40. 65.]

## NumPy 除了定義類別、函數，亦有定義常數 

Not a Number 可以表示「未定義」或「遺漏」的浮點數。

來源：<https://numpy.org/doc/stable/reference/constants.html>

In [35]:
print(np.nan)
print(type(np.nan))

nan
<class 'float'>

## 針對含有 `np.nan` 的 `ndarray` 有相對應名稱的聚合函數可以運算

- `np.sum()` vs. `np.nansum()`
- `np.mean()` vs. `np.nanmean()`
- ...等。

In [36]:
# Similar function names for array with np.nan
array_range = np.arange(1, 16, dtype=float).reshape(3, 5)
array_range[2, 4] = np.nan
print(array_range)
print(np.sum(array_range))
print(np.nansum(array_range))

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. nan]]
nan
105.0

## Pandas 的 `Index` 類別

使用 `pd.Index()` 函數創造 `Index` 類別的實例。

In [37]:
import numpy as np

In [38]:
primes_array = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29])
prime_indexes = pd.Index(primes_array)
print(prime_indexes)
print(type(prime_indexes))

Index([2, 3, 5, 7, 11, 13, 17, 19, 23, 29], dtype='int64')
<class 'pandas.core.indexes.base.Index'>

## `Index` 的基礎屬性

- `Index.dtype` 資料類別。
- `Index.size` 元素個數。

In [39]:
print(prime_indexes.dtype)
print(prime_indexes.size)

int64
10

## `Index` 類別結合 Python 內建的 `tuple` 與 `set` 兩種資料結構類別的特性

- 具有 `tuple` 無法更動的特性。
- 具有 `set` 集合運算的特性。

## `Index` 類別具有 `tuple` 無法更動的特性

In [40]:
# Index has the characteristics of a tuple
primes_array = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29])
prime_indexes = pd.Index(primes_array)
try:
    prime_indexes[-1] = 31
except TypeError as error_message:
    print(error_message)

Index does not support mutable operations

## `Index` 類別具有 `set` 集合運算的特性

In [41]:
# Index has the characteristics of a set
primes_array = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29])
prime_indexes = pd.Index(primes_array)
odd_indexes = pd.Index(np.arange(1, 30, 2))
print(prime_indexes)
print(odd_indexes)

Index([2, 3, 5, 7, 11, 13, 17, 19, 23, 29], dtype='int64')
Index([1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29], dtype='int64')

## `Index` 具有與 `set` 同樣名稱的集合運算方法

- `Index.intersection()` 交集。
- `Index.union()` 聯集。
- `Index.difference()` 差集。
- `Index.symmetric_difference()` 對稱差集。

In [42]:
# Set operations of Index
print(prime_indexes.intersection(odd_indexes))
print(prime_indexes.union(odd_indexes))
print(prime_indexes.difference(odd_indexes))
print(odd_indexes.difference(prime_indexes))
print(prime_indexes.symmetric_difference(odd_indexes))

Index([3, 5, 7, 11, 13, 17, 19, 23, 29], dtype='int64')
Index([1, 2, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29], dtype='int64')
Index([2], dtype='int64')
Index([1, 9, 15, 21, 25, 27], dtype='int64')
Index([1, 2, 9, 15, 21, 25, 27], dtype='int64')

## Pandas 的 `Series` 類別

使用 `pd.Series()` 函數創造 `Series` 類別的實例。

In [43]:
months_array = np.arange(1, 13)
months_series = pd.Series(months_array)
print(months_series)
print(type(months_series))

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
dtype: int64
<class 'pandas.core.series.Series'>

## `Series` 的基礎屬性與方法

- `Series.dtype` 資料類別。
- `Series.size` 元素個數。
- `Series.index` 取出 `Series` 的 `Index` 部分。  
- `Series.values` 取出 `Series` 的 `ndarray` 部分。
- `Series.astype()` 轉換 `Series` 的資料類別。

In [44]:
print(months_series.dtype)
print(months_series.size)

int64
12

## `Series` 由 `Index` 與 `ndarray` 組合而成

In [45]:
print(months_series.index)
print(type(months_series.index))

RangeIndex(start=0, stop=12, step=1)
<class 'pandas.core.indexes.range.RangeIndex'>

In [46]:
print(months_series.values)
print(type(months_series.values))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
<class 'numpy.ndarray'>

## 調整 `Series` 的 `Index`

- 在建立的時候指定。
- 透過 `Series.index` 更新。

## 在建立的時候指定

In [47]:
months_abbreviation = ["JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"]
months_series = pd.Series(months_array, index=months_abbreviation)
months_series

JAN     1
FEB     2
MAR     3
APR     4
MAY     5
JUN     6
JUL     7
AUG     8
SEP     9
OCT    10
NOV    11
DEC    12
dtype: int64

## 透過 `Series.index` 更新

In [48]:
months_abbreviation = ["JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"]
months_series = pd.Series(months_array)
months_series.index = months_abbreviation
months_series

JAN     1
FEB     2
MAR     3
APR     4
MAY     5
JUN     6
JUL     7
AUG     8
SEP     9
OCT    10
NOV    11
DEC    12
dtype: int64

## 如何取出 `Series` 中的元素

- 以元素位置 indexing/slicing
- 以 `Index` indexing/slicing

## 以元素位置 indexing/slicing

In [49]:
print(months_series[0])
print(months_series[:3])

1
JAN    1
FEB    2
MAR    3
dtype: int64

/var/folders/0b/r__z5mpn6ldgb_w2j7_y_ntr0000gn/T/ipykernel_90024/2814450207.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(months_series[0])

## 以 `Index` indexing/slicing

In [50]:
print(months_series["JAN"])
print(months_series["JAN":"MAR"])

1
JAN    1
FEB    2
MAR    3
dtype: int64

## 轉換 `Series` 的資料類別

- 在建立的時候指定。
- 透過 `Series.astype()` 轉換 `Series` 的資料類別。

## 在建立的時候指定

In [51]:
months_series = pd.Series(months_array, dtype=float)
months_series

0      1.0
1      2.0
2      3.0
3      4.0
4      5.0
5      6.0
6      7.0
7      8.0
8      9.0
9     10.0
10    11.0
11    12.0
dtype: float64

## `Series.astype()` 轉換 `Series` 的資料類別

In [52]:
months_series = pd.Series(months_array)
print(months_series.dtype)
print(months_series.astype(float))

int64
0      1.0
1      2.0
2      3.0
3      4.0
4      5.0
5      6.0
6      7.0
7      8.0
8      9.0
9     10.0
10    11.0
11    12.0
dtype: float64

## Pandas 的 `DataFrame` 類別

使用 `pd.DataFrame()` 函數創造 `DataFrame` 類別的實例。

- 輸入以欄為基準（Column-based）的資料內容。
- 輸入以列為基準（Row-based）的資料內容。

## 輸入以欄為基準（Column-based）的資料內容

In [53]:
movie_df = pd.DataFrame()
movie_df["title"] = ["The Shawshank Redemption", "The Dark Knight", "Schindler's List", "Forrest Gump", "Inception"]
movie_df["imdb_rating"] = [9.3, 9.0, 8.9, 8.8, 8.7]
movie_df["release_year"] = [1994, 2008, 1993, 1994, 2010]
print(movie_df)
print(type(movie_df))

                      title  imdb_rating  release_year
0  The Shawshank Redemption          9.3          1994
1           The Dark Knight          9.0          2008
2          Schindler's List          8.9          1993
3              Forrest Gump          8.8          1994
4                 Inception          8.7          2010
<class 'pandas.core.frame.DataFrame'>

## 輸入以列為基準（Row-based）的資料內容

In [54]:
movies = [
    {"title": "The Shawshank Redemption", "imdb_rating": 9.3, "release_year": 1994},
    {"title": "The Dark Knight", "imdb_rating": 9.0, "release_year": 2008},
    {"title": "Schindler's List", "imdb_rating": 8.9, "release_year": 1993},
    {"title": "Forrest Gump", "imdb_rating": 8.8, "release_year": 1994},
    {"title": "Inception", "imdb_rating": 8.7, "release_year": 2010},
]
movie_df = pd.DataFrame(movies)
print(movie_df)
print(type(movie_df))

                      title  imdb_rating  release_year
0  The Shawshank Redemption          9.3          1994
1           The Dark Knight          9.0          2008
2          Schindler's List          8.9          1993
3              Forrest Gump          8.8          1994
4                 Inception          8.7          2010
<class 'pandas.core.frame.DataFrame'>

## Jupyter Notebook 針對 `DataFrame` 類別有特別的顯示外觀

In [55]:
movie_df

                      title  imdb_rating  release_year
0  The Shawshank Redemption          9.3          1994
1           The Dark Knight          9.0          2008
2          Schindler's List          8.9          1993
3              Forrest Gump          8.8          1994
4                 Inception          8.7          2010

## `DataFrame` 的基礎屬性

- `DataFrame.dtypes` 資料類別。
- `DataFrame.shape` 外型。
- `DataFrame.index` 取出列標籤（row labels）部分。  
- `DataFrame.columns` 取出欄標籤（column labels）的部分。

In [56]:
print(movie_df.dtypes)
print(movie_df.shape)
print(movie_df.index)
print(movie_df.columns)

title            object
imdb_rating     float64
release_year      int64
dtype: object
(5, 3)
RangeIndex(start=0, stop=5, step=1)
Index(['title', 'imdb_rating', 'release_year'], dtype='object')

## `DataFrame` 由數個 `Series` 共享同一個 `Index` 組成

In [57]:
print(type(movie_df.index))
print(type(movie_df["title"]))
print(type(movie_df["imdb_rating"]))
print(type(movie_df["release_year"]))

<class 'pandas.core.indexes.range.RangeIndex'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>

## `DataFrame` 的基礎方法

- `DataFrame.head(n)` 檢視前 `n` 列。
- `DataFrame.tail(n)` 檢視後 `n` 列。
- `DataFrame.describe()`  檢視數值欄位的描述性統計。
- `DataFrame.info()` 檢視詳細資訊。

## 檢視前 `n` 列、後 `n` 列

- `DataFrame.head(n)` 檢視前 `n` 列。
- `DataFrame.tail(n)` 檢視後 `n` 列。

In [58]:
movie_df.head(3)

                      title  imdb_rating  release_year
0  The Shawshank Redemption          9.3          1994
1           The Dark Knight          9.0          2008
2          Schindler's List          8.9          1993

In [59]:
movie_df.tail(2)

          title  imdb_rating  release_year
3  Forrest Gump          8.8          1994
4     Inception          8.7          2010

## `DataFrame.describe()` 檢視數值欄位的描述性統計

In [60]:
movie_df.describe()

       imdb_rating  release_year
count     5.000000      5.000000
mean      8.940000   1999.800000
std       0.230217      8.438009
min       8.700000   1993.000000
25%       8.800000   1994.000000
50%       8.900000   1994.000000
75%       9.000000   2008.000000
max       9.300000   2010.000000

## `DataFrame.info()` 檢視詳細資訊

In [61]:
movie_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         5 non-null      object
 1   imdb_rating   5 non-null      float64
 2   release_year  5 non-null      int64
dtypes: float64(1), int64(1), object(1)
memory usage: 252.0+ bytes

## 常見的來源資料格式

1. 純文字檔案。
2. 試算表。
3. 關聯式資料庫中的資料表。

## 什麼是純文字檔案

只有文字所構成的電腦檔案，不包含字型的樣式或者段落標記，能夠使用最簡單的文字編輯器（例如 Windows 的「記事本」、macOS 的 TextEdit）直接開啟檢視。

## 更適合程式設計與資料科學的文字編輯器

- [Visual Studio Code](https://code.visualstudio.com/)
- [Atom](https://atom.io/)
- [Sublime Text](https://www.sublimetext.com/)
- [Notepad ++(for Windows only)](https://notepad-plus-plus.org/)

## 不同格式的純文字檔案

- 非結構化的純文字檔案。
- JSON(JavaScript Object Notation)
- 特定符號分隔的純文字檔案。

## 兩種路徑的標註方式

1. 絕對路徑：從根目錄開始標註
2. 相對路徑：從工作目錄（Current working directory）開始標註

## 什麼是 JSON

> JSON(JavaScript Object Notation) 是一種輕量的資料交換格式，對於人類而言是容易閱讀和寫作的格式，對於電腦而言是容易解析和建立的格式，簡言之，是一種對人類與電腦都友善的純文字格式，JSON 雖然源於 JavaScript，但卻是獨立於該程式語言之外，能夠被眾多程式語言輕鬆解析和建立的一種理想資料交換格式。JSON 可能由兩種資料結構組成：鍵值對應關係與有序列表，可以用 Python 的 `dict` 與 `list` 來理解。

來源：<https://www.json.org/json-en.html>

## 特定符號分隔的純文字檔案

- 透過特定符號分隔欄位的結構化資料。
- 常見的有逗號（`,`）、分號（`;`）、Tab 鍵（`\t`）等。
- 最廣泛使用的是逗號，因此有特定的副檔名 `.csv` 意指逗號分隔值（Comma-separated values）。

## 什麼是試算表

> 試算表是類比紙本計算表格的電腦軟體，由許多列與欄所構成的儲存格，其中可以存放數值、算式或文字。常見的試算表軟體有 Microsoft Excel、macOS Numbers 與 Google Sheets

來源：<https://en.wikipedia.org/wiki/Spreadsheet>

## 試算表檔案的組成

- 試算表的檔案為一個活頁簿（Workbook）、活頁簿中可以有多個試算表（Spreadsheets）
- `pd.read_excel()` 函數預設讀取第零張試算表（左邊數來第一張）。
- 可以透過 `pd.ExcelFile.sheet_names` 屬性檢視活頁簿中有幾個試算表。

## 什麼是關聯式資料庫中的資料表

> 關聯式資料庫（Relational database）是基於關聯模型所建構的資料庫，是儲存在電腦中的資料集合。一個資料庫中通常會有多個資料表（Table）能夠藉助集合運算（Set operation）等數學方法來處理資料表之間的操作和關聯，也能夠用來表示現實世界中的商業邏輯，並能夠接受結構化查詢語言 SQL 來進行檢索和操作。

來源：<https://en.wikipedia.org/wiki/Relational_database>

## 資料載入統整

- 使用 `json.load()` 函數搭配 `with` 敘述載入 JSON。
- 使用 `pd.read_csv()` 函數載入特定符號分隔的結構化純文字檔案。
- 使用 `pd.read_excel()` 函數載入試算表。
- 使用 `pd.read_sql()` 函數搭配資料庫連線（ODBC）載入關聯式資料庫的資料表。

## 多數的資料清理、資料外型與類別的轉換是面對 `DataFrame`

入門 Pandas 的第一步就是掌握 `Index`、`ndarray`、`Series` 與 `DataFrame` 四個資料結構類別彼此之間的關係。

- `Series` 由 `Index` 與 `ndarray` 組合而成。
- `DataFrame` 由數個共享同一個 `Index` 的 `Series` 組合而成。

## `DataFrame` 是有兩個維度的資料結構

- 第一個維度稱為觀測值（Observations），有時亦稱為列（Rows）
- 第二個維度稱為變數（Variables），有時亦稱為欄（Columns）
- 我們習慣以 `(m, n)` 或者 `m x n` 來描述一個具有 `m` 列觀測值、`n` 欄變數的 `DataFrame`

In [62]:
import pandas as pd

movies = pd.read_csv("https://raw.githubusercontent.com/datainpoint/classroom-landbank-2026/refs/heads/main/data/movies.csv")
print(movies.shape)
print(movies.head().shape)
movies.head() # just show the first 5 rows

(250, 6)
(5, 6)

,id,title,release_year,rating,director,runtime
0,1,The Shawshank Redemption,1994,9.3,Frank Darabont,142
1,2,The Godfather,1972,9.2,Francis Ford Coppola,175
2,3,The Godfather: Part II,1974,9.0,Francis Ford Coppola,202
3,4,The Dark Knight,2008,9.0,Christopher Nolan,152
4,5,12 Angry Men,1957,9.0,Sidney Lumet,96

## `DataFrame` 與二維 `ndarray` 不同的地方

- `DataFrame` 的每個變數可以是異質的。
- `DataFrame` 的觀測值具有列標籤（row-label）、變數具有欄標籤（column-label）

In [63]:
print(movies.dtypes)  # heterogeneous 
print(movies.index)   # row-label
print(movies.columns) # column-label

id                int64
title            object
release_year      int64
rating          float64
director         object
runtime           int64
dtype: object
RangeIndex(start=0, stop=250, step=1)
Index(['id', 'title', 'release_year', 'rating', 'director', 'runtime'], dtype='object')

## 什麼是乾淨資料

1. 每個變數有自己的欄位。
2. 每個觀測值有自己的資料列。
3. 每個列、欄標籤與值的對應有自己的儲存格。

來源：<https://r4ds.had.co.nz/tidy-data.html>

## 不乾淨資料有著各自的樣態

> Tidy datasets are all alike, but every messy dataset is messy in its own way.
>
> Hadley Wickham

來源：<https://r4ds.had.co.nz/tidy-data.html>

## Pandas 使用更直觀的概念操作資料

- 如何定義「更直觀」？
    - 像操作試算表一般（Spreadsheet-like）
    - 像使用結構化查詢語言一般（SQL-like）

## 以 `DataFrame["column"]` 選擇欄位成為外型 `(m,)` 的 `Series`

In [64]:
print(type(movies["title"]))
print(movies["title"].shape)
movies["title"]

<class 'pandas.core.series.Series'>
(250,)

0                            The Shawshank Redemption
1                                       The Godfather
2                              The Godfather: Part II
3                                     The Dark Knight
4                                        12 Angry Men
                            ...
245    Neon Genesis Evangelion: The End of Evangelion
246                                7 Kogustaki Mucize
247                                        Tangerines
248                                          Drishyam
249                                            Swades
Name: title, Length: 250, dtype: object

## 以 `DataFrame[["column"]]` 選擇欄位成為外型 `(m, 1)` 的 `DataFrame`

In [65]:
print(type(movies[["title"]]))
print(movies[["title"]].shape)
movies[["title"]]

<class 'pandas.core.frame.DataFrame'>
(250, 1)

                                              title
0                          The Shawshank Redemption
1                                     The Godfather
2                            The Godfather: Part II
3                                   The Dark Knight
4                                      12 Angry Men
..                                              ...
245  Neon Genesis Evangelion: The End of Evangelion
246                              7 Kogustaki Mucize
247                                      Tangerines
248                                        Drishyam
249                                          Swades

[250 rows x 1 columns]

## 以 `DataFrame[["column_0", "column_1", ...]]` 選擇多個欄位成為外型 `(m, n)` 的 `DataFrame`

運用 Fancy indexing 於欄位的選擇。

In [66]:
movies[["title", "director", "release_year", "rating"]]

,title,director,release_year,rating
0,The Shawshank Redemption,Frank Darabont,1994,9.3
1,The Godfather,Francis Ford Coppola,1972,9.2
2,The Godfather: Part II,Francis Ford Coppola,1974,9.0
3,The Dark Knight,Christopher Nolan,2008,9.0
4,12 Angry Men,Sidney Lumet,1957,9.0
...,...,...,...,...
245,Neon Genesis Evangelion: The End of Evangelion,Hideaki Anno,1997,8.1
246,7 Kogustaki Mucize,Mehmet Ada Öztekin,2019,8.2
247,Tangerines,Zaza Urushadze,2013,8.2
248,Drishyam,Nishikant Kamat,2015,8.2
249,Swades,Ashutosh Gowariker,2004,8.2

## 以 `DataFrame.loc[:, [column_0, column_1, ...]]` 選擇多個欄位成為外型 `(m, n)` 的 `DataFrame`

- `loc` 是透過資料位置（Location）指定，也就是根據欄標籤選擇。
- `:` 表示不針對資料列篩選。

In [67]:
movies.loc[:, ["title", "director", "release_year", "rating"]]

,title,director,release_year,rating
0,The Shawshank Redemption,Frank Darabont,1994,9.3
1,The Godfather,Francis Ford Coppola,1972,9.2
2,The Godfather: Part II,Francis Ford Coppola,1974,9.0
3,The Dark Knight,Christopher Nolan,2008,9.0
4,12 Angry Men,Sidney Lumet,1957,9.0
...,...,...,...,...
245,Neon Genesis Evangelion: The End of Evangelion,Hideaki Anno,1997,8.1
246,7 Kogustaki Mucize,Mehmet Ada Öztekin,2019,8.2
247,Tangerines,Zaza Urushadze,2013,8.2
248,Drishyam,Nishikant Kamat,2015,8.2
249,Swades,Ashutosh Gowariker,2004,8.2

## 以 `DataFrame.iloc[:, [0, 1, ...]]` 選擇多個欄位成為外型 `(m, n)` 的 `DataFrame`

- `iloc` 是透過資料整數位置（Integer location）指定，也就是根據欄的整數位置選擇。
- `:` 表示不針對資料列篩選。

In [68]:
movies.iloc[:, [1, 4, 2, 3]]

,title,director,release_year,rating
0,The Shawshank Redemption,Frank Darabont,1994,9.3
1,The Godfather,Francis Ford Coppola,1972,9.2
2,The Godfather: Part II,Francis Ford Coppola,1974,9.0
3,The Dark Knight,Christopher Nolan,2008,9.0
4,12 Angry Men,Sidney Lumet,1957,9.0
...,...,...,...,...
245,Neon Genesis Evangelion: The End of Evangelion,Hideaki Anno,1997,8.1
246,7 Kogustaki Mucize,Mehmet Ada Öztekin,2019,8.2
247,Tangerines,Zaza Urushadze,2013,8.2
248,Drishyam,Nishikant Kamat,2015,8.2
249,Swades,Ashutosh Gowariker,2004,8.2

## 善用 `Series` 的特性

- `Series` 是由 `Index` 與 `ndarray` 組合而成，具備了 `ndarray` 的特性。
- 善用元素操作（Elementwise）運算。
- 善用特殊的 indexing 語法：Fancy indexing/Boolean indexing

## 透過列標籤（row-label）篩選資料列

- 在 `movies` 中魔戒三部曲分別位於列標籤 6, 9, 13
    - `loc` 是透過資料位置（Location）指定，也就是根據列標籤篩選。
    - `:` 表示不針對欄位選擇。
- 運用 Fancy indexing 於資料列的篩選。

In [69]:
movies.loc[[6, 9, 13], :]

,id,title,release_year,rating,director,runtime
6,7,The Lord of the Rings: The Return of the King,2003,8.9,Peter Jackson,201
9,10,The Lord of the Rings: The Fellowship of the Ring,2001,8.8,Peter Jackson,178
13,14,The Lord of the Rings: The Two Towers,2002,8.7,Peter Jackson,179

## 以 `DataFrame.iloc[[0, 1, ...], :]` 選擇多個資料列

- 在 `lord_of_the_rings` 中第一集與第三集分別位於第 0, 1 列。
    - `iloc` 是透過資料整數位置（Integer location）指定，也就是根據列的整數位置篩選。
    - `:` 表示不針對欄位選擇。
- 運用 Fancy indexing 於資料列的篩選。

In [70]:
lord_of_the_rings = movies.loc[[6, 9, 13], :]
lord_of_the_rings.iloc[[0, 1], :]

,id,title,release_year,rating,director,runtime
6,7,The Lord of the Rings: The Return of the King,2003,8.9,Peter Jackson,201
9,10,The Lord of the Rings: The Fellowship of the Ring,2001,8.8,Peter Jackson,178

## 區分 `DataFrame` 的兩種索引語法

- `DataFrame.loc[row-label, column-label]` 以列、欄標籤為準。
- `DataFrame.iloc[row-integer-location, column-integer-location]` 以列、欄整數位置為準。

## 透過條件敘述以 `DataFrame[booleans]` 篩選資料列

- 運用 Boolean indexing 於資料列的篩選。
- 熟悉之後會直接將條件敘述寫在中括號裡。

In [71]:
boolean_series = movies["director"] == "Peter Jackson"
movies[boolean_series] # movies[movies["director"] == "Peter Jackson"]

,id,title,release_year,rating,director,runtime
6,7,The Lord of the Rings: The Return of the King,2003,8.9,Peter Jackson,201
9,10,The Lord of the Rings: The Fellowship of the Ring,2001,8.8,Peter Jackson,178
13,14,The Lord of the Rings: The Two Towers,2002,8.7,Peter Jackson,179

## 如何負面表列（negate）由 `bool` 組成的 Series

- 使用相反的關係運算符 `==` vs. `!=`
- 使用 `~` 運算符。

In [72]:
boolean_series = movies["director"] != "Peter Jackson"
print(boolean_series.sum())
boolean_series = movies["director"] == "Peter Jackson"
print((~boolean_series).sum())

247
247

## 加入多個條件敘述篩選資料列

- 運用 `&` 運算符**交集**多個條件敘述。
- 運用 `|` 運算符**聯集**多個條件敘述。

## 運用 `&` 運算符交集多個條件敘述

In [73]:
(movies["release_year"] == 1994) & (movies["rating"] >= 8.8)

0       True
1      False
2      False
3      False
4      False
       ...
245    False
246    False
247    False
248    False
249    False
Length: 250, dtype: bool

In [74]:
movies[(movies["release_year"] == 1994) & (movies["rating"] >= 8.8)] # movies released in 1994 with amazing rating score

,id,title,release_year,rating,director,runtime
0,1,The Shawshank Redemption,1994,9.3,Frank Darabont,142
7,8,Pulp Fiction,1994,8.9,Quentin Tarantino,154
11,12,Forrest Gump,1994,8.8,Robert Zemeckis,142

## 運用 `|` 運算符聯集多個條件敘述

In [75]:
(movies["release_year"] == 1994) | (movies["rating"] >= 8.8)

0       True
1       True
2       True
3       True
4       True
       ...
245    False
246    False
247    False
248    False
249    False
Length: 250, dtype: bool

In [76]:
movies[(movies["release_year"] == 1994) | (movies["rating"] >= 8.8)]

,id,title,release_year,rating,director,runtime
0,1,The Shawshank Redemption,1994,9.3,Frank Darabont,142
1,2,The Godfather,1972,9.2,Francis Ford Coppola,175
2,3,The Godfather: Part II,1974,9.0,Francis Ford Coppola,202
3,4,The Dark Knight,2008,9.0,Christopher Nolan,152
4,5,12 Angry Men,1957,9.0,Sidney Lumet,96
5,6,Schindler's List,1993,8.9,Steven Spielberg,195
6,7,The Lord of the Rings: The Return of the King,2003,8.9,Peter Jackson,201
7,8,Pulp Fiction,1994,8.9,Quentin Tarantino,154
8,9,"The Good, the Bad and the Ugly",1966,8.8,Sergio Leone,178
9,10,The Lord of the Rings: The Fellowship of the Ring,2001,8.8,Peter Jackson,178
10,11,Fight Club,1999,8.8,David Fincher,139
11,12,Forrest Gump,1994,8.8,Robert Zemeckis,142
12,13,Inception,2010,8.8,Christopher Nolan,148
30,31,Léon: The Professional,1994,8.5,Luc Besson,110
33,34,The Lion King,1994,8.5,Roger Allers,88

## 運用 `Series.isin()` 聯集單一變數的多個條件

In [77]:
movies[movies["director"].isin(["Peter Jackson", "Quentin Tarantino"])]

,id,title,release_year,rating,director,runtime
6,7,The Lord of the Rings: The Return of the King,2003,8.9,Peter Jackson,201
7,8,Pulp Fiction,1994,8.9,Quentin Tarantino,154
9,10,The Lord of the Rings: The Fellowship of the Ring,2001,8.8,Peter Jackson,178
13,14,The Lord of the Rings: The Two Towers,2002,8.7,Peter Jackson,179
56,57,Django Unchained,2012,8.4,Quentin Tarantino,165
84,85,Inglourious Basterds,2009,8.3,Quentin Tarantino,153
88,89,Reservoir Dogs,1992,8.3,Quentin Tarantino,99
173,174,Kill Bill: Vol. 1,2003,8.1,Quentin Tarantino,111

In [78]:
movies[movies["release_year"].isin([1994, 2008])]

,id,title,release_year,rating,director,runtime
0,1,The Shawshank Redemption,1994,9.3,Frank Darabont,142
3,4,The Dark Knight,2008,9.0,Christopher Nolan,152
7,8,Pulp Fiction,1994,8.9,Quentin Tarantino,154
11,12,Forrest Gump,1994,8.8,Robert Zemeckis,142
30,31,Léon: The Professional,1994,8.5,Luc Besson,110
33,34,The Lion King,1994,8.5,Roger Allers,88
60,61,WALL·E,2008,8.4,Andrew Stanton,98
181,182,Gran Torino,2008,8.1,Clint Eastwood,116

## 如何判斷條件敘述的交集或聯集

- 運用語言邏輯思考條件的結合為「和」還是「或」，「和」為交集、「或」為聯集。
- 運用資料列數思考條件的結合要「縮減」還是「擴增」，「縮減」為交集、「擴增」為聯集。

## 兩個排序方式

1. 遞增（又稱升冪）排序，預設的排序方式。
2. 遞減（又稱降冪）排序。

## 使用 `DataFrame` 的兩個方法排序

- `DataFrame.sort_index()` 依列標籤排序。
- `DataFrame.sort_values()` 依欄位排序。

## `DataFrame.sort_index()` 依列標籤排序 

預設 `ascending=True`

In [79]:
movies.sort_index()

,id,title,release_year,rating,director,runtime
0,1,The Shawshank Redemption,1994,9.3,Frank Darabont,142
1,2,The Godfather,1972,9.2,Francis Ford Coppola,175
2,3,The Godfather: Part II,1974,9.0,Francis Ford Coppola,202
3,4,The Dark Knight,2008,9.0,Christopher Nolan,152
4,5,12 Angry Men,1957,9.0,Sidney Lumet,96
...,...,...,...,...,...,...
245,246,Neon Genesis Evangelion: The End of Evangelion,1997,8.1,Hideaki Anno,87
246,247,7 Kogustaki Mucize,2019,8.2,Mehmet Ada Öztekin,132
247,248,Tangerines,2013,8.2,Zaza Urushadze,87
248,249,Drishyam,2015,8.2,Nishikant Kamat,163
249,250,Swades,2004,8.2,Ashutosh Gowariker,189

In [80]:
movies.sort_index(ascending=False)

,id,title,release_year,rating,director,runtime
249,250,Swades,2004,8.2,Ashutosh Gowariker,189
248,249,Drishyam,2015,8.2,Nishikant Kamat,163
247,248,Tangerines,2013,8.2,Zaza Urushadze,87
246,247,7 Kogustaki Mucize,2019,8.2,Mehmet Ada Öztekin,132
245,246,Neon Genesis Evangelion: The End of Evangelion,1997,8.1,Hideaki Anno,87
...,...,...,...,...,...,...
4,5,12 Angry Men,1957,9.0,Sidney Lumet,96
3,4,The Dark Knight,2008,9.0,Christopher Nolan,152
2,3,The Godfather: Part II,1974,9.0,Francis Ford Coppola,202
1,2,The Godfather,1972,9.2,Francis Ford Coppola,175
0,1,The Shawshank Redemption,1994,9.3,Frank Darabont,142

## `DataFrame.sort_values()` 依欄位排序

- 預設 `ascending=True`
- 數值由小到大、英文由 A 到 Z

In [81]:
movies.sort_values("release_year")

,id,title,release_year,rating,director,runtime
98,99,The Kid,1921,8.3,Charles Chaplin,68
194,195,Sherlock Jr.,1924,8.2,Buster Keaton,45
152,153,The Gold Rush,1925,8.2,Charles Chaplin,95
198,199,The General,1926,8.1,Clyde Bruckman,67
115,116,Metropolis,1927,8.3,Fritz Lang,153
...,...,...,...,...,...,...
246,247,7 Kogustaki Mucize,2019,8.2,Mehmet Ada Öztekin,132
164,165,Klaus,2019,8.2,Sergio Pablos,96
230,231,Soul,2020,8.1,Pete Docter,100
58,59,Hamilton,2020,8.5,Thomas Kail,160
166,167,Zack Snyder's Justice League,2021,8.3,Zack Snyder,242

In [82]:
movies.sort_values("release_year", ascending=False)

,id,title,release_year,rating,director,runtime
166,167,Zack Snyder's Justice League,2021,8.3,Zack Snyder,242
58,59,Hamilton,2020,8.5,Thomas Kail,160
230,231,Soul,2020,8.1,Pete Docter,100
75,76,Avengers: Endgame,2019,8.4,Anthony Russo,181
246,247,7 Kogustaki Mucize,2019,8.2,Mehmet Ada Öztekin,132
...,...,...,...,...,...,...
115,116,Metropolis,1927,8.3,Fritz Lang,153
198,199,The General,1926,8.1,Clyde Bruckman,67
152,153,The Gold Rush,1925,8.2,Charles Chaplin,95
194,195,Sherlock Jr.,1924,8.2,Buster Keaton,45
98,99,The Kid,1921,8.3,Charles Chaplin,68

## 傳入 `list` 指定多個欄位與排序方式

In [83]:
movies.sort_values(["release_year", "title"], ascending=[False, True])

,id,title,release_year,rating,director,runtime
166,167,Zack Snyder's Justice League,2021,8.3,Zack Snyder,242
58,59,Hamilton,2020,8.5,Thomas Kail,160
230,231,Soul,2020,8.1,Pete Docter,100
107,108,1917,2019,8.3,Sam Mendes,119
246,247,7 Kogustaki Mucize,2019,8.2,Mehmet Ada Öztekin,132
...,...,...,...,...,...,...
115,116,Metropolis,1927,8.3,Fritz Lang,153
198,199,The General,1926,8.1,Clyde Bruckman,67
152,153,The Gold Rush,1925,8.2,Charles Chaplin,95
194,195,Sherlock Jr.,1924,8.2,Buster Keaton,45
98,99,The Kid,1921,8.3,Charles Chaplin,68

## 使用 `Series` 的聚合方法取得欄位摘要

- `Series.count()` 不含未定義值的列數
- `Series.sum()` 加總
- `Series.max()` 最大值
- `Series.min()` 最小值
- `Series.mean()` 平均
- ...等。

## 片長 `runtime` 的摘要

In [84]:
print(movies["runtime"].max())
print(movies["runtime"].min())

321
45

## IMDb 評等 `rating` 的摘要

In [85]:
print(movies["rating"].max())
print(movies["rating"].min())
print(movies["rating"].mean())

9.3
8.1
8.305200000000001

## 使用 `DataFrame.groupby()` 獲得排序後的獨一值 `DataFrameGroupBy` 類別

In [86]:
print(movies.groupby("director"))

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x10755f1d0>

## 分組後接續選擇欄位以及聚合方法

In [87]:
movies.groupby("director")["title"].count() # number of movies by director

director
Aamir Khan               1
Adam Elliot              1
Akira Kurosawa           6
Alejandro G. Iñárritu    1
Alfred Hitchcock         6
                        ..
Yasujirô Ozu             1
Yavuz Turgul             1
Zack Snyder              1
Zaza Urushadze           1
Çagan Irmak              1
Name: title, Length: 157, dtype: int64

In [88]:
movies.groupby("director")["rating"].mean() # average rating by director

director
Aamir Khan               8.400000
Adam Elliot              8.100000
Akira Kurosawa           8.316667
Alejandro G. Iñárritu    8.100000
Alfred Hitchcock         8.300000
                           ...
Yasujirô Ozu             8.200000
Yavuz Turgul             8.200000
Zack Snyder              8.300000
Zaza Urushadze           8.200000
Çagan Irmak              8.300000
Name: rating, Length: 157, dtype: float64

## 善用三個技巧衍生計算欄位

1. 元素操作（Elementwise）運算。
2. 使用函數或 `Series` 的方法。
3. 使用 `Series.map()`

## 元素操作（Elementwise）運算

In [89]:
print(movies["runtime"] // 60) # hours
print(movies["runtime"] % 60)  # minutes

0      2
1      2
2      3
3      2
4      1
      ..
245    1
246    2
247    1
248    2
249    3
Name: runtime, Length: 250, dtype: int64
0      22
1      55
2      22
3      32
4      36
       ..
245    27
246    12
247    27
248    43
249     9
Name: runtime, Length: 250, dtype: int64

## 使用函數或 `Series` 的方法

In [90]:
hours = (movies["runtime"] // 60).astype(str)
minutes = (movies["runtime"] % 60).astype(str)
hours.str.cat(minutes, sep=":") # hours:minutes

0      2:22
1      2:55
2      3:22
3      2:32
4      1:36
       ...
245    1:27
246    2:12
247    1:27
248    2:43
249     3:9
Name: runtime, Length: 250, dtype: object

## 使用 `Series.map()`

In [91]:
def mins_to_hourmins(x: int) -> str:
    hours = str(x // 60)
    minutes = str(x % 60)
    return f"{hours.zfill(2)}:{minutes.zfill(2)}" # 2 digits zero-filled

runtime_hours_mins = movies["runtime"].map(mins_to_hourmins)
runtime_hours_mins

0      02:22
1      02:55
2      03:22
3      02:32
4      01:36
       ...
245    01:27
246    02:12
247    01:27
248    02:43
249    03:09
Name: runtime, Length: 250, dtype: object

## 使用 `DataFrame.insert()` 新增變數

留意 `DataFrame.insert()` 更新的機制是更新物件本身並回傳 `None`

In [92]:
print(movies.columns)
n = movies.shape[1]
movies.insert(n, "runtime_hours_mins", runtime_hours_mins)
print(movies.columns)
movies.head()

Index(['id', 'title', 'release_year', 'rating', 'director', 'runtime'], dtype='object')
Index(['id', 'title', 'release_year', 'rating', 'director', 'runtime',
       'runtime_hours_mins'],
      dtype='object')

,id,title,release_year,rating,director,runtime,runtime_hours_mins
0,1,The Shawshank Redemption,1994,9.3,Frank Darabont,142,02:22
1,2,The Godfather,1972,9.2,Francis Ford Coppola,175,02:55
2,3,The Godfather: Part II,1974,9.0,Francis Ford Coppola,202,03:22
3,4,The Dark Knight,2008,9.0,Christopher Nolan,152,02:32
4,5,12 Angry Men,1957,9.0,Sidney Lumet,96,01:36

## 如何調整列標籤與欄標籤

- 使用 `DataFrame.set_index()` 指定欄位取代目前的列標籤。
- 使用 `DataFrame.reset_index()` 重設列標籤。
- 指定 `DataFrame.columns` 調整欄標籤。

## 使用 `DataFrame.set_index()` 指定欄位取代目前的列標籤

In [93]:
movies.set_index("title")

,id,release_year,rating,director,runtime,runtime_hours_mins
title,,,,,,
The Shawshank Redemption,1,1994,9.3,Frank Darabont,142,02:22
The Godfather,2,1972,9.2,Francis Ford Coppola,175,02:55
The Godfather: Part II,3,1974,9.0,Francis Ford Coppola,202,03:22
The Dark Knight,4,2008,9.0,Christopher Nolan,152,02:32
12 Angry Men,5,1957,9.0,Sidney Lumet,96,01:36
...,...,...,...,...,...,...
Neon Genesis Evangelion: The End of Evangelion,246,1997,8.1,Hideaki Anno,87,01:27
7 Kogustaki Mucize,247,2019,8.2,Mehmet Ada Öztekin,132,02:12
Tangerines,248,2013,8.2,Zaza Urushadze,87,01:27
Drishyam,249,2015,8.2,Nishikant Kamat,163,02:43
Swades,250,2004,8.2,Ashutosh Gowariker,189,03:09

## 使用 `DataFrame.reset_index()` 重設列標籤

預設以 `RangeIndex` 重設後將原本的列標籤變為第零個欄位。

In [94]:
movies.set_index("title").reset_index()

,title,id,release_year,rating,director,runtime,runtime_hours_mins
0,The Shawshank Redemption,1,1994,9.3,Frank Darabont,142,02:22
1,The Godfather,2,1972,9.2,Francis Ford Coppola,175,02:55
2,The Godfather: Part II,3,1974,9.0,Francis Ford Coppola,202,03:22
3,The Dark Knight,4,2008,9.0,Christopher Nolan,152,02:32
4,12 Angry Men,5,1957,9.0,Sidney Lumet,96,01:36
...,...,...,...,...,...,...,...
245,Neon Genesis Evangelion: The End of Evangelion,246,1997,8.1,Hideaki Anno,87,01:27
246,7 Kogustaki Mucize,247,2019,8.2,Mehmet Ada Öztekin,132,02:12
247,Tangerines,248,2013,8.2,Zaza Urushadze,87,01:27
248,Drishyam,249,2015,8.2,Nishikant Kamat,163,02:43
249,Swades,250,2004,8.2,Ashutosh Gowariker,189,03:09

## 使用 `DataFrame.reset_index()` 重設列標籤（續）

設定參數 `drop=True` 以 `RangeIndex` 重設後捨棄原本的列標籤。

In [95]:
movies.set_index("title").reset_index(drop=True)

,id,release_year,rating,director,runtime,runtime_hours_mins
0,1,1994,9.3,Frank Darabont,142,02:22
1,2,1972,9.2,Francis Ford Coppola,175,02:55
2,3,1974,9.0,Francis Ford Coppola,202,03:22
3,4,2008,9.0,Christopher Nolan,152,02:32
4,5,1957,9.0,Sidney Lumet,96,01:36
...,...,...,...,...,...,...
245,246,1997,8.1,Hideaki Anno,87,01:27
246,247,2019,8.2,Mehmet Ada Öztekin,132,02:12
247,248,2013,8.2,Zaza Urushadze,87,01:27
248,249,2015,8.2,Nishikant Kamat,163,02:43
249,250,2004,8.2,Ashutosh Gowariker,189,03:09

## 指定 `DataFrame.columns` 調整欄標籤

In [96]:
print(movies.columns)
movies.columns = [column.upper() for column in movies.columns]
print(movies.columns)

Index(['id', 'title', 'release_year', 'rating', 'director', 'runtime',
       'runtime_hours_mins'],
      dtype='object')
Index(['ID', 'TITLE', 'RELEASE_YEAR', 'RATING', 'DIRECTOR', 'RUNTIME',
       'RUNTIME_HOURS_MINS'],
      dtype='object')

## 處理多個變數的分組聚合結果

如果在 `DataFrame.groupby()` 輸入了多個變數作為分組依據 `[column_0, column_1, ...]` 輸出的 `Series` 會有特殊的 `MultiIndex` 類別。

In [97]:
movies = pd.read_csv("https://raw.githubusercontent.com/datainpoint/classroom-landbank-2026/refs/heads/main/data/movies.csv")
movies_by_year_director = movies.groupby(["release_year", "director"])["title"].count()
movies_by_year_director.index

MultiIndex([(1921,     'Charles Chaplin'),
            (1924,       'Buster Keaton'),
            (1925,     'Charles Chaplin'),
            (1926,      'Clyde Bruckman'),
            (1927,          'Fritz Lang'),
            (1928, 'Carl Theodor Dreyer'),
            (1931,     'Charles Chaplin'),
            (1931,          'Fritz Lang'),
            (1934,         'Frank Capra'),
            (1936,     'Charles Chaplin'),
            ...
            (2019,        'Bong Joon Ho'),
            (2019,      'Céline Sciamma'),
            (2019,       'James Mangold'),
            (2019,  'Mehmet Ada Öztekin'),
            (2019,          'Sam Mendes'),
            (2019,       'Sergio Pablos'),
            (2019,       'Todd Phillips'),
            (2020,         'Pete Docter'),
            (2020,         'Thomas Kail'),
            (2021,         'Zack Snyder')],
           names=['release_year', 'director'], length=247)

## 如何操作 `MultiIndex` 類別

- 以操作 `tuple` 的方式面對 `MultiIndex` 類別。
- 使用 `DataFrame.reset_index()` 重設列標籤。

## 以操作 `tuple` 的方式面對 `MultiIndex` 類別

In [98]:
movies_by_year_director[(2008, )]

director
Andrew Stanton       1
Christopher Nolan    1
Clint Eastwood       1
Name: title, dtype: int64

In [99]:
movies_by_year_director[(2008, "Christopher Nolan")]

1

## 使用 `DataFrame.reset_index()` 重設列標籤

In [100]:
movies_by_year_director.reset_index()

     release_year         director  title
0            1921  Charles Chaplin      1
1            1924    Buster Keaton      1
2            1925  Charles Chaplin      1
3            1926   Clyde Bruckman      1
4            1927       Fritz Lang      1
..            ...              ...    ...
242          2019    Sergio Pablos      1
243          2019    Todd Phillips      1
244          2020      Pete Docter      1
245          2020      Thomas Kail      1
246          2021      Zack Snyder      1

[247 rows x 3 columns]

## 個案討論：使用 Python 數據分析模組實踐「財務自由的世界，財務分析就是一場投資的戰爭」的部分選股程序

## 下載資料集

[datasets.zip](https://classroom-hahow-learn-python-with-stock-data.s3.ap-northeast-1.amazonaws.com/datasets.zip)

## 實作：檢視各小組題目中 Python 數據分析模組的需求，以 mock data 測試能否順利完成