# 土地銀行數位種子人才發展計劃

> Python 資料處理與金融分析應用

[郭耀仁](https://hahow.in/@tonykuoyj) | <yaojenkuo@ntu.edu.tw>

## 目錄

- Python 數據分析模組介紹（P.3）
- NumPy 基本概念與應用（P.18）
- Pandas 資料讀取、清洗與整理（P.34）
- 個案實作：使用 Python 數據分析模組實踐「財務自由的世界，財務分析就是一場投資的戰爭」（P.62）
- 分組討論：檢視各小組題目中 Python 數據分析模組的需求（P.75）

## Python 數據分析模組介紹

## Python 數據分析模組

- NumPy
- Pandas
- Scikit-Learn
- Matplotlib.PyPlot

## 什麼是 NumPy

> NumPy 是 Numeric Python 的簡稱，是 Python 最重要的資料科學模組之一。NumPy 創造了 `ndarray` 的資料結構類別以及大量的通用函數與聚合函數，讓 Python 使用者能夠對進行快速的數值計算、使用統計函數、進行線性代數運算以及操作隨機的模擬任務等。

來源：<https://numpy.org/>

## （沒什麼用的冷知識）NumPy 的前身為兩個模組

- 1990 年代中期誕生的` Numeric` 與 `Numarray` 模組。
- NumPy 於 2005 集兩者之大成問世。

來源：<https://www.nature.com/articles/s41586-020-2649-2>

## 根據說明文件的範例載入

來源：<https://numpy.org/doc/stable/user/absolute_beginners.html#how-to-import-numpy>

In [1]:
import numpy as np

## NumPy 的核心功能

1. 使用 `ndarray` 來進行數值操作。
2. 使用模組定義的函數對 `ndarray` 進行數值運算。
3. `ndarray` 是其他資料科學模組 Pandas、Matplotlib 與 Scikit-Learn 的基石。

## 什麼是 Pandas

> Pandas 是 Python 處理表格式資料（Tabular data）的第三方模組，它創造了 `Index`、`Series` 與 `DataFrame` 的資料結構類別，讓 Python 在面對表格式資料時能夠用更直覺的觀念操作。

來源：<https://github.com/pandas-dev/pandas>

## （沒什麼用的冷知識）Pandas 跟熊貓「沒有關係」

1. **Pan**el(自從版本 0.20.0 之後棄用)
2. **Da**taFrame
3. **S**eries

![](https://media.giphy.com/media/46Zj6ze2Z2t4k/giphy.gif)

來源：<https://media.giphy.com/media/46Zj6ze2Z2t4k/giphy.gif>

## 根據說明文件的範例載入

來源：<https://pandas.pydata.org/docs/user_guide/10min.html>

In [2]:
import pandas as pd

## 入門 Pandas 的第一步就是掌握 `Index`、`ndarray`、`Series` 與 `DataFrame` 四個資料結構類別彼此之間的關係

- `Series` 由 `Index` 與 `ndarray` 組合而成。
- `DataFrame` 由數個共享同一個 `Index` 的 `Series` 組合而成。

## 什麼是 Scikit-Learn

> Scikit-learn 是 Python 機器學習的第三方模組，透過它可以進行監督式以及非監督式學習，提供了模型訓練、資料預處理、模型選擇以及模型評估等功能。

來源：<https://scikit-learn.org>

## （沒什麼用的冷知識）Scikit-Learn 是最受歡迎的 SciKit(SciPy Toolkit)

- Scikit-Learn 與 Scikit-Image 是兩個最受歡迎、維護最良善的 Scikits
- 還有眾多其他的 Scikits

來源：<https://projects.scipy.org/scikits.html>

## 根據說明文件的範例載入

多數時候我們使用 Scikit-Learn 中的特定類別或函數，因此以 `from sklearn import FUNCTION/CLASS` 載入特定類別或函數，而非 `import sklearn`

來源：<https://scikit-learn.org/stable/getting_started.html>

## 為什麼選擇 Scikit-Learn

- 簡潔、一致且設計良善的應用程式介面設計，只要理解基礎用法和語法，就能延伸切換到其他的演算法或模型。
- 文件撰寫完整而豐富。
- 維護良善。

## Scikit-Learn 應用程式介面設計原則

1. 一致性。
2. 可檢查性。
3. 不擴增新類別。
4. 可組合性。
5. 合理預設參數。

## NumPy 基本概念與應用

## 常用的 `ndarray` 屬性

- `ndarray.ndim` 維度數。
- `ndarray.shape` 外型。
- `ndarray.size` 元素個數。
- `ndarray.dtype` 資料類別。

In [3]:
prime_list = [2, 3, 5, 7, 11]
prime_array = np.array(prime_list)
print(prime_array.ndim)
print(prime_array.shape)
print(prime_array.size)
print(prime_array.dtype)

1
(5,)
5
int64

## 不同維度數的 `ndarray` 有不同的暱稱

- 零維 `ndarray`：純量（Scalar）。
- 一維 `ndarray`：向量（Vector）。
- 二維 `ndarray`：矩陣（Matrix）。
- 三維或者 n 維 `ndarray`：張量（Tensor）。

## 純量、向量、矩陣與張量外型示意圖

![Imgur](https://i.imgur.com/81fM6Hf.png)

來源：<https://dev.to/juancarlospaco/tensors-for-busy-people-315k>

## `ndarray` 與 `list` 相同的地方

- indexing/slicing 的語法。
- 能夠以 indexing 更新。

## indexing 的語法

`ndarray` 採用兩個方向的索引機制：

1. 由左至右：「從 0 開始」的索引機制。
2. 由右至左：「從 -1 開始」的索引機制。

In [4]:
print("From start to stop:")
print(prime_array[0])
print(prime_array[1])
print(prime_array[2])
print(prime_array[3])
print(prime_array[prime_array.size - 1])

From start to stop:
2
3
5
7
11

In [5]:
print("From stop to start:")
print(prime_array[-1])
print(prime_array[-2])
print(prime_array[-3])
print(prime_array[-4])
print(prime_array[-prime_array.size])

From stop to start:
11
7
5
3
2

## slicing `[start:stop:step]`

除了可以取出特定位置的單個資料值，`ndarray` 也支援擷取特定片段，藉此獲得一個較短長度 `ndarray` 的語法。

- `start` 起始位置（包含）。
- `stop` 終止位置（排除）。
- `step` 間隔。

In [6]:
print(prime_array[::])   # default
print(prime_array[::2])  # step=2
print(prime_array[:3])   # stop=5, exclusive
print(prime_array[3:])   # start=5, inclusive
print(prime_array[::-1]) # step=-1, reverse

[ 2  3  5  7 11]
[ 2  5 11]
[2 3 5]
[ 7 11]
[11  7  5  3  2]

## 能夠以 indexing 更新

In [7]:
print(prime_array)   # before update
prime_array[-1] = 13 # update
print(prime_array)   # after update

[ 2  3  5  7 11]
[ 2  3  5  7 13]

## `ndarray` 與 `list` 相異的地方

- indexing 二維以上的 `ndarray` 可以用更便捷的語法 `[i, j, k, ...]`
- 同質性資料結構類別。
- 支援元素操作（Elementwise）運算。
- 支援特殊的 indexing 語法。

## indexing 二維以上的 `ndarray` 可以用 `ndarray` 便捷的語法 `[i, j, k, ...]`

In [8]:
matrix = np.array([[5, 5],
                   [6, 6],
                   [55, 66]])
print(matrix)
print(matrix[2, 1]) # 66 locates at [2, 1]

[[ 5  5]
 [ 6  6]
 [55 66]]
66

In [9]:
print(matrix[:, 1])
print(matrix[:, [1]]) # keep dimension

[ 5  6 66]
[[ 5]
 [ 6]
 [66]]

## 同質性資料結構類別

In [10]:
heterogeneous_list = [False, True, 5566, 55.66, 'Luke Skywalker']
for element in heterogeneous_list:
    print(type(element))

<class 'bool'>
<class 'bool'>
<class 'int'>
<class 'float'>
<class 'str'>

In [11]:
homogeneous_array = np.array(heterogeneous_list)
for element in homogeneous_array:
    print(type(element))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>

## 支援元素操作（Elementwise）運算

In [12]:
# list does not support elementwise
try:
    prime_list**2
except TypeError as error_message:
    print(error_message)

unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [13]:
# ndarray supports elementwise
prime_array = np.array(prime_list)
prime_array**2

array([  4,   9,  25,  49, 121])

## 支援特殊的 indexing 語法

- Fancy indexing
- Boolean indexing

## 什麼是 Fancy indexing

對應 `ndarray` 時中括號允許傳入 `list`，藉此可以更有彈性地取出 `ndarray` 中的元素。

In [14]:
try:
    prime_list[[0, 1, 4]]
except TypeError as error_message:
    print(error_message)

list indices must be integers or slices, not list

In [15]:
print(prime_array[[0, 1, 4]])

[ 2  3 11]

## 什麼是 Boolean indexing

對應 `ndarray` 時中括號允許傳入由 `bool` 組成的相同長度 `list` 或 `ndarray`，藉此可以更有彈性地取出 `ndarray` 中的元素。

In [16]:
prime_list = [2, 3, 5, 7, 11]
try:
    prime_list[[False, True, True, True, True]]
except TypeError as error_message:
    print(error_message)

list indices must be integers or slices, not list

In [17]:
prime_array = np.array([2, 3, 5, 7, 11])
print(prime_array)
print(prime_array[[False, True, True, True, True]])
print(prime_array % 2 == 1)
print(prime_array[prime_array % 2 == 1])

[ 2  3  5  7 11]
[ 3  5  7 11]
[False  True  True  True  True]
[ 3  5  7 11]

## Pandas 資料讀取、清洗與整理

## Pandas 資料讀取

- CSV 檔案：`pd.read_csv()`
- 特定格式的 JSON 檔案：`pd.read_json()`
- Excel 活頁簿/試算表：`pd.read_excel()`
- 資料庫資料表：`pd.read_sql()`

來源：<https://pandas.pydata.org/docs/user_guide/io.html>

## 什麼是乾淨資料

1. 每個變數有自己的欄位。
2. 每個觀測值有自己的資料列。
3. 每個列、欄標籤與值的對應有自己的儲存格。

來源：<https://r4ds.had.co.nz/tidy-data.html>

## 不乾淨資料有著各自的樣態

> Tidy datasets are all alike, but every messy dataset is messy in its own way.
>
> Hadley Wickham

來源：<https://r4ds.had.co.nz/tidy-data.html>

## Pandas 使用更直觀的概念操作資料

- 如何定義「更直觀」？
    - 像操作試算表一般（Spreadsheet-like）
    - 像使用結構化查詢語言一般（SQL-like）

## `DataFrame` 是有兩個維度的資料結構

- 第一個維度稱為觀測值（Observations），有時亦稱為列（Rows）
- 第二個維度稱為變數（Variables），有時亦稱為欄（Columns）
- 我們習慣以 `(m, n)` 或者 `m x n` 來描述一個具有 `m` 列觀測值、`n` 欄變數的 `DataFrame`

## `DataFrame` 與二維 `ndarray` 不同的地方

- `DataFrame` 的每個變數可以是異質的。
- `DataFrame` 的觀測值具有列標籤（row-label）、變數具有欄標籤（column-label）

## `DataFrame` 的基礎屬性

- `DataFrame.dtypes` 資料類別。
- `DataFrame.shape` 外型。
- `DataFrame.index` 取出列標籤（row labels）部分。  
- `DataFrame.columns` 取出欄標籤（column labels）的部分。

## `DataFrame` 的基礎方法

- `DataFrame.head(n)` 檢視前 `n` 列。
- `DataFrame.tail(n)` 檢視後 `n` 列。
- `DataFrame.describe()`  檢視數值欄位的描述性統計。
- `DataFrame.info()` 檢視詳細資訊。

## 檢視前 `n` 列、後 `n` 列

- `DataFrame.head(n)` 檢視前 `n` 列。
- `DataFrame.tail(n)` 檢視後 `n` 列。

In [18]:
top_ranking_stocks = pd.read_csv("top_ranking_stocks.csv")
top_ranking_stocks.head(3)

    ticker stock   price recorded_on
0  6515.TW    穎崴  9630.0  2026-05-10
1  7769.TW    鴻勁  5800.0  2026-05-10
2  2059.TW    川湖  5320.0  2026-05-10

In [19]:
top_ranking_stocks.tail(2)

       ticker stock  price recorded_on
198  3611.TWO    鼎翰  190.0  2026-05-10
199  5903.TWO    全家  189.5  2026-05-10

## `DataFrame.describe()` 檢視數值欄位的描述性統計

In [20]:
top_ranking_stocks.describe()

              price
count    200.000000
mean    1042.654750
std     1704.792351
min      189.500000
25%      316.625000
50%      467.500000
75%      880.250000
max    16955.000000

## `DataFrame.info()` 檢視詳細資訊

In [21]:
top_ranking_stocks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ticker       200 non-null    object
 1   stock        200 non-null    object
 2   price        200 non-null    float64
 3   recorded_on  200 non-null    object
dtypes: float64(1), object(3)
memory usage: 6.4+ KB

## 以 `DataFrame["column"]` 選擇欄位成為外型 `(m,)` 的 `Series`

In [22]:
top_ranking_stocks["stock"]

0      穎崴
1      鴻勁
2      川湖
3      創意
4      緯穎
       ..
195    耀穎
196    科嶠
197    翔名
198    鼎翰
199    全家
Name: stock, Length: 200, dtype: object

## 以 `DataFrame[["column"]]` 選擇欄位成為外型 `(m, 1)` 的 `DataFrame`

In [23]:
top_ranking_stocks[["stock"]]

    stock
0      穎崴
1      鴻勁
2      川湖
3      創意
4      緯穎
..    ...
195    耀穎
196    科嶠
197    翔名
198    鼎翰
199    全家

[200 rows x 1 columns]

## 以 `DataFrame[["column_0", "column_1", ...]]` 選擇多個欄位成為外型 `(m, n)` 的 `DataFrame`

運用 Fancy indexing 於欄位的選擇。

In [24]:
top_ranking_stocks[["ticker", "stock"]]

       ticker stock
0     6515.TW    穎崴
1     7769.TW    鴻勁
2     2059.TW    川湖
3     3443.TW    創意
4     6669.TW    緯穎
..        ...   ...
195  7772.TWO    耀穎
196  4542.TWO    科嶠
197  8091.TWO    翔名
198  3611.TWO    鼎翰
199  5903.TWO    全家

[200 rows x 2 columns]

## 透過條件敘述以 `DataFrame[booleans]` 篩選資料列

- 運用 Boolean indexing 於資料列的篩選。
- 熟悉之後會直接將條件敘述寫在中括號裡。

```python
boolean_series = top_ranking_stocks["price"] >= 1000
top_ranking_stocks[boolean_series] # top_ranking_stocks[top_ranking_stocks["price"] >= 1000]
```

## 如何負面表列（negate）由 `bool` 組成的 Series

- 使用相反的關係運算符 `>=` vs. `<`
- 使用 `~` 運算符。

## 加入多個條件敘述篩選資料列

- 運用 `&` 運算符**交集**多個條件敘述。
- 運用 `|` 運算符**聯集**多個條件敘述。
- 運用 `Series.isin()` 聯集單一變數的多個條件。

## 如何判斷條件敘述的交集或聯集

- 運用語言邏輯思考條件的結合為「和」還是「或」，「和」為交集、「或」為聯集。
- 運用資料列數思考條件的結合要「縮減」還是「擴增」，「縮減」為交集、「擴增」為聯集。

## 兩個排序方式

1. 遞增（又稱升冪）排序，預設的排序方式。
2. 遞減（又稱降冪）排序。

## 使用 `DataFrame` 的兩個方法排序

- `DataFrame.sort_index()` 依列標籤排序。
- `DataFrame.sort_values()` 依欄位排序。

## `DataFrame.sort_index()` 依列標籤排序 

預設 `ascending=True`

```python
top_ranking_stocks.sort_index()
top_ranking_stocks.sort_index(ascending=False)
```

## `DataFrame.sort_values()` 依欄位排序

- 預設 `ascending=True`
- 數值由小到大、英文由 A 到 Z

```python
top_ranking_stocks.sort_values("price")
top_ranking_stocks.sort_values("price", ascending=False)
```

## 使用 `Series` 的聚合方法取得欄位摘要

- `Series.count()` 不含未定義值的列數
- `Series.sum()` 加總
- `Series.max()` 最大值
- `Series.min()` 最小值
- `Series.mean()` 平均
- ...等。

In [25]:
print(top_ranking_stocks["price"].max())
print(top_ranking_stocks["price"].min())
print(top_ranking_stocks["price"].mean())

16955.0
189.5
1042.6547500000001

## 善用三個技巧衍生計算欄位

1. 元素操作（Elementwise）運算。
2. 使用函數或 `Series` 的方法。
3. 使用 `Series.map()`

In [26]:
def categorize_stock_type(x: str):
    if ".TWO" in x:
        return "上櫃"
    else:
        return "上市"

stock_type_ser = top_ranking_stocks["ticker"].map(categorize_stock_type)

## 使用 `DataFrame.insert()` 新增變數

留意 `DataFrame.insert()` 更新的機制是更新物件本身並回傳 `None`

In [27]:
n = top_ranking_stocks.shape[1]
top_ranking_stocks.insert(n, "stock_type", stock_type_ser)
top_ranking_stocks.head()

    ticker stock   price recorded_on stock_type
0  6515.TW    穎崴  9630.0  2026-05-10         上市
1  7769.TW    鴻勁  5800.0  2026-05-10         上市
2  2059.TW    川湖  5320.0  2026-05-10         上市
3  3443.TW    創意  5210.0  2026-05-10         上市
4  6669.TW    緯穎  5200.0  2026-05-10         上市

## 使用 `DataFrame.groupby()` 獲得排序後的獨一值 `DataFrameGroupBy` 類別

In [28]:
print(top_ranking_stocks.groupby("stock_type"))

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x10fa9c490>

## 分組後接續選擇欄位以及聚合方法

In [29]:
top_ranking_stocks.groupby("stock_type")["price"].max()

stock_type
上市     9630.0
上櫃    16955.0
Name: price, dtype: float64

## 個案實作：使用 Python 數據分析模組實踐「財務自由的世界，財務分析就是一場投資的戰爭」

## 下載資料集

[datasets.zip](https://classroom-hahow-learn-python-with-stock-data.s3.ap-northeast-1.amazonaws.com/datasets.zip)

## 阿宅師擇股意志之傳承：財務分析上菜的十一道標準程序

1. 選出上市公司股價前四十名與上櫃公司股價前三十名的公司。
2. **丟棄掛牌不到兩年的公司，以及在開曼群島註冊的 F 頭文字股票（現為字尾 -KY）**。
3. 將過去四年曾經產生虧損的公司剔除掉。
4. 剔除過去八季（嚴格一點可挑十二季）其單季營業利益率曾大幅度上下起伏與連續大幅下滑的公司。
5. 剔除過去三年累積自由現金流量為負數者。
6. 選擇近三個月的合併營收年增率至少要維持正數者。
7. 剔除過去三年曾經辦理現金增資的公司。
8. 剔除市值50億以下的公司。
9. 剔除存貨周轉率連續下滑的公司。
10. 剔除成交量過低的公司（總大私房定義：十日均量不能低於自己打算買進部位的十倍）。
11. 與惡名昭彰的股市名嘴斷！捨！離！

## 實作一：剔除在開曼群島註冊的公司

- 使用的金融數據為 `datasets` 中的 `top_ranking_stocks.csv`
- 金融數據擷取來源：
    - [台股上市股價排行](https://tw.stock.yahoo.com/rank/price?exchange=TAI)
    - [台股上櫃股價排行](https://tw.stock.yahoo.com/rank/price?exchange=TWO)

## 剔除在開曼群島註冊的公司的論述

- 開曼群島公司承銷所得的股款幾乎全數匯往外國，而非留在台灣的金融市場。
- 開曼群島公司的資料與營業狀況無從稽核。
- 實證研究：
    - 書中統計 2010-2012 年掛牌上市的 33 間開曼群島公司，在掛牌日以收盤價買進，持有一年後虧損的家數佔 72%
    - 同一批公司在兩年後總計自由現金流量為「淨流出」681 億元。

## 使用 Excel 對照

- 首先將 `top_ranking_stocks.csv` 載入至 Excel 試算表。
- 運用 `SEARCH()` 函數，辨識股票名稱中是否包含 `"-KY"` 的文字特徵。
- 運用 `ISNUMBER()` 函數將整數轉換為 `TRUE` 將 `#VALUE!` 轉換為 `FALSE`

## 實作一步驟：使用 Python 的做法

- 首先將 `top_ranking_stocks.csv` 上傳至 Google Colab 的工作目錄。
- 可以用 Google Colab 的純文字編輯器預覽內容。
- 載入 `pandas` 模組並且取別名為 `pd`
- 使用 `pd.read_csv()` 函數載入為 `DataFrame`
- 使用 `Series.str.contains()` 方法辨識股票名稱中是否包含 `"-KY"` 的文字特徵。
- 運用布林索引（Boolean indexing）的技巧。
- 給予每列觀測值一個布林值（`False`/`True`），可以將對應為 `True` 的觀測值保留下來。
- 注意 `is_ky_registry` 判斷的 `True` 是對應在開曼群島註冊的公司，若是要剔除，必須加入 `not` 的運算，將 `False`/`True` 互換。

```python
data_frame_with_true_rows = data_frame[booleans]
```

```python
import pandas as pd

file_path = "top_ranking_stocks.csv"
top_ranking_stocks_csv = pd.read_csv(file_path)
stock_names = top_ranking_stocks_csv["stock"]
is_ky_registry = stock_names.str.contains("-KY")
is_not_ky_registry = ~is_ky_registry
mission_two_result = top_ranking_stocks_csv[is_not_ky_registry]
```

## 實作二：剔除掛牌不到兩年的公司

- 使用的金融數據為 `datasets` 中的 `listing_dates.csv`
- 金融數據擷取來源：[MOPS 公開資訊觀測站](https://mops.twse.com.tw/mops/#/web/t05st03)

## 剔除掛牌不到兩年的公司的論述

- 多數新掛牌的公司是大集團的關係企業或上下游廠商，大集團將獲利較佳、前景展望看好的產品與訂單轉給這些公司承作讓財務績效「看起來」相當亮眼是很常見且容易的操作。
- 新掛牌公司的股權為大股東關係人持有，股價容易被「刻意地」拉抬；掛牌的主要動機是籌資，市場術語為「出貨」，大股東有強烈誘因在股價拉抬後賣掉持股，從金融市場套現。
- 實證研究：
    - 書中統計 2006-2010 年間新掛牌後三個月內股價曾經超過 100 元的 54 間公司，僅有 3 間在 2012 年 7 月股價仍維持在 100 元以上。
    - 同一批公司中有 16 間的最大跌幅超過 90%、38 間的最大跌幅超過 80%。

## 使用 Excel 對照

- 首先將 `listing_dates.csv` 載入至 Excel 試算表。
- 運用 `ISBLANK()` 函數，辨識是否有上市上櫃日期（ETF 沒有市上櫃日期）。
- 運用 `TODAY()` 函數取得今天日期。
- 將今天日期與上市上櫃日期相減，可以得到掛牌天數，判斷掛牌天數是否超過 2 年（`365 * 2`）
- 運用 `AND()` 函數將「有上市上櫃日期」與「掛牌天數超過 2 年」這兩個條件交集。

## 實作二步驟：使用 Python 的做法

- 首先將 `listing_dates.csv` 上傳至 Google Colab 的工作目錄。
- 載入 `pandas` 模組並且取別名為 `pd`
- 使用 `pd.read_csv()` 函數載入為 `DataFrame`
- 使用 `Series.notna()` 方法辨識上市上櫃日期是否「非未定義值」。
- 使用 `datetime.today()` 函數取得今天日期，並轉換成 `Series`。
- 使用 `pd.to_datetime()` 函數將上市上櫃日期轉換成可計算的日期型別。
- 將今天日期與上市上櫃日期相減，可以得到掛牌天數，判斷掛牌天數是否超過 2 年（`365 * 2`）。
- 以 `&` 運算符交集「有上市上櫃日期」與「掛牌天數超過 2 年」這兩個條件。
- 利用布林索引剔除「沒有上市上櫃日期」以及「掛牌不到兩年的公司」。

```python
from datetime import date
import pandas as pd

file_path = "listing_dates.csv"
listing_dates_csv = pd.read_csv(file_path)
today = date.today()
today_ser = pd.to_datetime(today)
listing_date_ser = pd.to_datetime(listing_dates_csv["listing_date"])
listing_days = today_ser - listing_date_ser
listing_days = listing_days.dt.days
listing_date_notna = listing_dates_csv["listing_date"].notna()
days_of_two_years = 365*2
is_listing_days_over_two_years = listing_days > days_of_two_years
conditions_intersected = listing_date_notna & is_listing_days_over_two_years
listing_dates_csv[conditions_intersected]
```

## 分組討論：檢視各小組題目中 Python 數據分析模組的需求

## 特徵工程需求盤點

- 是否有資料表連接（Concatenate/Join/Merge）的需求？
- 是否有衍生計算欄位的需求？
- 是否有標準化的需求？
- 是否有連續型數值轉換為離散型數值的需求？
- 是否有類別變數要加入建模的需求？
- 是否有變數相關矩陣（Correlation matrix）的需求？
- 是否有變數重要性（Feature importance）的需求？

## 建模需求盤點

- 監督式學習
    - 是否有預測連續值的需求？
    - 是否有預測機率、預測離散值的需求？
- 非監督式學習
    - 是否有分群的需求？
    - 是否有降維的需求？

## 問題解決（Problem solving）的檢核點

- 是否有使用「假說推論樹」後向推導出解題脈絡？
- 是否有討論出「反直覺、反經驗」的假說？
- 是否有提出業務的機會點或痛點作為問題來源？
- 是否有列出關鍵的決策者、利益關係人？
- 是否有列出問題解決的指標為何？
- 分析的結果能否對應到行動方案？
- 是否有列出問題、行動方案的限制為何？
- 是否有列出可以尋求的支持及資源？

## 資料科學框架（Data science pipeline）的檢核點

- 是否已經完成資料來源盤點？
- Wrangle(資料載入 Import、清理 Tidy、轉換型別或外型 Transform) 是否已經試做？
- Visualise 資料視覺化是否已經試做？
- Model 模型是否已經有想法？
- Program 程式設計是否已經試做？
- Communicate 故事是否已經順過脈絡？

## 行動方案（Action plan）的檢核點

- 是否有預計的損益表？是否有人力天數的估算？
- 是否有衡量財務效益與行動難易度，辨識出財務效益高且行動難度低的方案？
- 是否有列出責任歸屬、時間表與具體步驟？

## 成果發表（Presentation）的檢核點

- 是否已經決定簡報人選？
- 投入與產出不必是 1:1，有沒有評估過小組的槓桿能力？
- 是否有掌握 80/20 法則？能否把握開頭的 2 分鐘？
- 是否暸解聽眾的偏好？
- 是否妥善運用亞里斯多德的溝通三要素？